### PR TITLE
Adding a "hide" parameter to increase privacy

### PR DESCRIPTION
**Pull request by harivyasi**
Embedding YouTube videos on an HTML page as a side-effect of decreasing privacy for users. Leaving the (mis)use of cookies aside, even the act of loading a page with an embedded video is detrimental to privacy because the server(s) of the hosting platform is contacted to fetch the embedded element.

As a solution, I have implemented a "hide" parameter that marks the `div` of every video with `style.display = "none"` and adds an HTML button to flip this to `style.display = "block"`. Once clicked, the embed video appears and the button disappears.

I have tried to make the parameter a bit more versatile than a simple Boolean value. It can take in `True`, `False` or a title string for the video that's hidden behind the button.

A preview of things look like with the parameter is as follows:

When no title is given (i.e. `hide: True`):
WhenTitleIsNotGiven

When no title is given (i.e. `hide: Here's the title of my video`):
WhenTitleIsGiven

When the parameter is not used, or set to False, or when the button has been clicked:
AfterClicking

### CODE REVIEW

**Comment by harivyasi** [comment]
@dham Please have a look; some of my colleagues would like to use the feature. :)

**Review by dham — CHANGES_REQUESTED** [review]
Thanks for the PR! I see why you would want to do this, but I'm not quite convinced that this plugin is where it should be done. I think the job of this plugin is just to insert videos. If you want to wrap this in a context which controls whether or not the content is displayed, then there are (at least) two sphinx plugins that will do that: 
https://pypi.org/project/sphinxcontrib-details-directive/
and 
https://github.com/executablebooks/sphinx-panels/tree/master/sphinx_panels

For example, my website: https://object-oriented-python.github.io/1_introduction.html has videos hidden by default using sphinx-panels . The source is at https://github.com/object-oriented-python/object-oriented-programming/blob/master/doc/source/1_introduction.rst and a nicer version of the source using sphinx-contrib/details and the PR I'm about to merge here is at: https://github.com/object-oriented-python/object-oriented-programming/blob/vimeo/doc/source/1_introduction.rst . 

I think I'd need convincing that there is something important that can't be done by composing this plugin with one of those before I'd consider adding that functionality here. Of course if I am missing something important please tell me!

Cheers,

David

**Comment by harivyasi** [comment]
Hi David

Thanks for the quick response.

Here a bit of a background: I was asked by colleagues if I can have a look into a video embed blocking feature so as to respect privacy choices. So far they have been placing YT links instead of embeds to do so.

Upon a quick look, I found this repo as it is part of the `sphinx-contrib` and figured that I would like to stick to it because it is closest to an official thing for sphinx.

As you suggested, I considered using the `sphinx-panels` (albeit not the `details` directive) for the task at hand. But the fact that it would entail using another extension (i.e. adding more dependencies) for what could be included in this extension with a few lines of code was an amber light to me. Using the `details` directive would similarly entail having an extra extension.

If we can gather anything from #9, we know that these extensions can be difficult to maintain and quickly result in a dependency hell for end users. So given a choice between including a piece of code here and making it more self-contained and relying on other extensions, I would personally pick the former. Beyond this justification -- of minimizing dependencies -- I have no other for this PR. Still, just having the parameter would have an added implication that the _creator_ of the HTML page would also give privacy a thought; which I believe is a good thing.

Best
Shashank

PS. In the process of exploring this repo, I had already checked the `vimeo` branch and the platform agnostic way this extension is headed. (I quite like it.) If we agree on the above, I can then (by the weekend) send a PR for that branch including the same feature and saving duplication effort on your part.

**Comment by harivyasi** [comment]
Hi David

I noticed later that you went ahead and merged the `vimeo` branch into `master`. I have modified this PR to reflect the same. Please let me know of your decision, I will proceed in my private workflow accordingly.

NB: The present `master` imports `typing-extensions` which I believe is not used in the code. But it breaks the `make`  command anyway because the package is not installed as a requirement.

Best
Shashank

**Comment by dham** [comment]
I have to say that I still feel a bit uneasy about this. The essence of programming is composability, so I think that the right way to put a video directive inside something that hides it is to compose directives, rather than adding options onto the video directive. What if I want to put two videos behind one button? Or a video and some text? This PR feels a bit like a hack for one particular use case, rather than a general solution. As I mentioned above, I think that the general solution already exists. I'm not really convinced that the inconvenience of installing an additional plugin outweighs this.

Thanks for your comment about `typing-extensions`, though it has me confused since I can't find that module in `master`, and I don't believe I added it. We also don't use `make` in this package...

David

**Comment by harivyasi** [comment]
Hi again

Thanks for letting me know. As I said, there was little to the PR beyond expanding the functionality of the extension. On the other hand, I understand your point as well: it's best if a tool does one thing and does that best. Which this one does thanks to you. So all's good.

As for the `typing-extensions`, I branched out of `vimeo` in order to bring my fork up to speed and so had that in my code. As for the `make` breaking, I meant that it breaks when using `make html` to compile a sphinx-docs setup. (Make would do try running the extension when it finds the directive and then break because the `typing-extensions` module won't be installed). But as you mention; it wasn't there in the `master` so all's good on that end as well :D 

Cheers
Shashank

**Comment by rkdarst** [comment]
I'd really like this feature - "privacy mode" is one thing, but my ideal sphinx site would also not make any external requests unless explicitely asked.  But it makes sense that one tool does one thing.

I tried all of these:
- sphinx-panels
- sphinxcontrib-details-directive
- sphinx-togglebutton
- this PR

... and at least in Chrome, and the ones I tested with firefox, the network inspector shows that there *are* requests to the platform_url even before it is expanded!  I wonder if there was some change in browser behavior from then to now?

Any possible ideas?  I guess this specific feature isn't that common, so most other of the hide/show extensions don't target that use case.

**Pull request closed without merging**
